### ISSUE TITLE
Should warn or remove empty class if passed

### ISSUE THREAD

**Issue by hhsnopek** [reshape/sugarml#26]
```
// sugarml
ul.#list

// html
<ul class id="list">
```

Either the class attribute should be dropped or a warning should be prompted

**Comment by hhsnopek** [comment]
A warning or error should be thrown if a trailing period is found as well, see #27

**Comment by jescalan** [comment]
Well technically that dot means to add an empty class, this seems like the correct behavior to me...

**Comment by hhsnopek** [comment]
but why would we want to add to the markup if nothing exists? every byte counts when it comes to performance!

**Comment by jescalan** [comment]
I don't know honestly, why would someone put a period in there if they didn't want to add a class? You can just remove the extra period and the empty class will be gone.

**Comment by hhsnopek** [comment]
right - I understand that but if there's a trailing period or a period that has no name following it, it has the possibility to cause issues like #27 ...

**Comment by jescalan** [comment]
I get it, but that's a user error. #27 is not an issue, it's a documented feature. If you have a trailing period, this is because you want to use a content block. If you have a period with no classname, it's because you want the class property on the div but without a name. Both of these are working exactly how they are supposed to work, I don't see an opportunity for a change or an error message here...
